### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by psu1989** [zcqsntr/retro_matrix#1]
Do you have a more detailed wiring diagram you can share/?
Thanks!

**Comment by zcqsntr** [comment]
Hey! sorry I missed this. I used the Adafruit-hat, for that did all the wiring for me, I think there is a diagram in the rpi-rgb library READMEs somewhere, and probably elsewhere on the internet

**Comment by psu1989** [comment]
I plugged the power directly in to the hat.  I can't see in the pic how you wired the power.

**Comment by zcqsntr** [comment]
Oh right, I plugged it into the matrix in the end, but it doesn't actually matter. If you got the demos working then the matrix is wired up correctly. My app might not be displaying properly if you need to add additional command line arguments for the rpi-rgb library, but these will depend on your configuration
