### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by zcqsntr** [zcqsntr/retro_matrix#2]
./setup.sh works part way and then: In file included from mylib.cc:1: mylib.h:6:10: fatal error: led-matrix.h: No such file or directory #include "led-matrix.h" ~~~~~~~~~~~~~ compilation terminated. make: *** [Makefile:39: mylib.o] Error 1 make: Leaving directory '/home/pi/Desktop/retro_matrix/lib' g++ -o run_retro_matrix.o -I/home/pi/Desktop/retro_matrix/rpi-rgb-led-matrix/include -I. -I/home/pi/Desktop/retro_matrix/cellular_automata/game_of_life -I/home/pi/Desktop/retro_matrix/lib -I/usr/local/include/libevdev-1.0/libevdev -Wall -O3 -g -Wextra -Wno-unused-parameter --std=c++17 -I/home/pi/Desktop/retro_matrix/menus -c run_retro_matrix.cc In file included from run_retro_matrix.cc:4: retro_matrix.h:5:10: fatal error: libevdev.h: No such file or directory #include "libevdev.h" ~~~~~~~~~~~ compilation terminated. make: *** [Makefile:54: run_retro_matrix.o] Error 1
in lib\makefile this path does not exist RGB_LIB_DISTRIBUTION=/home/pi/Desktop/LED_matrix/rpi-rgb-led-matrix edited to RGB_LIB_DISTRIBUTION=/home/pi/Desktop/retro_matrix/rpi-rgb-led-matrix
now this error In file included from mylib.cc:1: mylib.h:10:10: fatal error: libevdev.h: No such file or directory #include "libevdev.h" ~~~~~~~~~~~ compilation terminated. make: *** [Makefile:39: mylib.o] Error 1 make: Leaving directory '/home/pi/Desktop/retro_matrix/lib' g++ -o run_retro_matrix.o -I/home/pi/Desktop/retro_matrix/rpi-rgb-led-matrix/include -I. -I/home/pi/Desktop/retro_matrix/cellular_automata/game_of_life -I/home/pi/Desktop/retro_matrix/lib -I/usr/local/include/libevdev-1.0/libevdev -Wall -O3 -g -Wextra -Wno-unused-parameter --std=c++17 -I/home/pi/Desktop/retro_matrix/menus -c run_retro_matrix.cc In file included from run_retro_matrix.cc:4: retro_matrix.h:5:10: fatal error: libevdev.h: No such file or directory #include "libevdev.h" ~~~~~~~~~~~ compilation terminated.

**Comment by psu1989** [comment]
also this:

./setup.sh 
works part way and then:
	In file included from mylib.cc:1:
	mylib.h:6:10: fatal error: led-matrix.h: No such file or directory
	 #include "led-matrix.h"
			  ^~~~~~~~~~~~~~
	compilation terminated.
	make: *** [Makefile:39: mylib.o] Error 1
	make: Leaving directory '/home/pi/Desktop/retro_matrix/lib'
	g++ -o run_retro_matrix.o -I/home/pi/Desktop/retro_matrix/rpi-rgb-led-matrix/include -I. -I/home/pi/Desktop/retro_matrix/cellular_automata/game_of_life -I/home/pi/Desktop/retro_matrix/lib  -I/usr/local/include/libevdev-1.0/libevdev -Wall -O3 -g -Wextra -Wno-unused-parameter --std=c++17  -I/home/pi/Desktop/retro_matrix/menus -c run_retro_matrix.cc
	In file included from run_retro_matrix.cc:4:
	retro_matrix.h:5:10: fatal error: libevdev.h: No such file or directory
	 #include "libevdev.h"
			  ^~~~~~~~~~~~
	compilation terminated.
	make: *** [Makefile:54: run_retro_matrix.o] Error 1

in lib\makefile



this path does not exist
RGB_LIB_DISTRIBUTION=/home/pi/Desktop/LED_matrix/rpi-rgb-led-matrix
edited to
RGB_LIB_DISTRIBUTION=/home/pi/Desktop/retro_matrix/rpi-rgb-led-matrix

**Comment by zcqsntr** [comment]
Thanks a lot for adding that, I might try and have a look at this tomorrow just to get it compiling, although tbh the whole thing needs a bit of a tidy up. You should just be able to run the executable without compiling though and it may or may not work depending on your setup

**Comment by zcqsntr** [comment]
So I've had a look and basically at the moment all the compilation paths are hardcoded. Ill have to fix all this with the general update to improve install ability which I will try and get to over the next month or so!
